services:
  tweet_analysis_agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tweet_analysis_agent
    ports:
      - "3773:3773"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}


    env_file:
      - .env
    volumes:
      - ./tweet_analysis_agent:/app/tweet_analysis_agent
      - ./agent_config.json:/app/agent_config.json
    restart: unless-stopped
    networks:
      - tweet_analysis_agent-network


networks:
  tweet_analysis_agent-network:
    driver: bridge
